"use strict";

(function initializeDom(app) {
  app.dom = {
    btnCategoria: document.getElementById("categoria"),
    registrar: document.getElementById("registro"),
    ordens: document.getElementById("ordens"),
    pesquisar: document.getElementById("buscar"),
    paragrafoErrBusca: document.getElementById("paragrafo_busca"),
    tabela: document.getElementById("tabela-produtos"),
    corpoTabela: document.getElementById("corpo-tabela"),
    filtroOpcoes: document.getElementById("filtro-opcoes"),
    btnAplicarFiltro: document.getElementById("aplicar_filtro"),
    btnLimparFiltro: document.getElementById("limpar_filtro"),
    btnRecarregarLista: document.getElementById("recarregar_lista"),
    btnInicio: document.getElementById("inicio-inventario"),
    btnVoltar: document.getElementById("voltar-inventario"),
    btnProximaPagina: document.getElementById("proximo-inventario"),
    btnUltimo: document.getElementById("ultimo-inventario"),
    abrirPopUpCategoria: document.getElementById("popup-categorias"),
    btnFecharCategoria: document.getElementById("btn-fechar-categorias"),
    inputCategoria: document.getElementById("nova-categoria"),
    selcionarCategoria: document.getElementById("select_categoria"),
    listaCategorias: document.getElementById("lista-categorias"),
    paragrafoErroCate: document.getElementById("erro_categoria"),
    formCategorias: document.getElementById("form-categorias"),
    btnSalvarCategoria: document.getElementById("adicionar-categoria"),
    btnEditarCategoria: document.getElementById("editar-categorias"),
    textoEdCat: document.getElementById("texto-ed-cat"),
    btnExcluirCat: document.getElementById("excluir-cat"),
    btnInicioCategorias: document.getElementById("inicio-categorias"),
    btnVoltarCategorias: document.getElementById("voltar-categorias"),
    btnProximaCategorias: document.getElementById("proximo-categorias"),
    btnUltimoCategorias: document.getElementById("ultimo-categorias"),
    popup: document.getElementById("popup"),
    botaoFecharPopUp: document.getElementById("btn-fechar"),
    form: document.getElementById("formulario"),
    codigo: document.getElementById("codigo"),
    nome: document.getElementById("nome-produto"),
    quantidade: document.getElementById("quantidade"),
    paragrafoErroRegistro: document.getElementById("erro-registro"),
    ES: document.getElementById("ES"),
    consumoMes: document.getElementById("consumo-mes"),
    consumo: document.getElementById("consumo"),
    prazoEntrega: document.getElementById("prazo-entrega"),
    abrirPainelOrdens: document.getElementById("popup_ordens"),
    btnFecharOrdem: document.getElementById("btnFechar_ordens"),
    procurarOrdens: document.getElementById("buscar_ordens"),
    paragrafoErroBuscar: document.getElementById("paragrafo_buscar_ordens"),
    atualizarTabelaOrdens: document.getElementById("todas_ordens"),
    btnCompraEntrada: document.getElementById("compra_entrada"),
    btnSaidaVenda: document.getElementById("saida_venda"),
    tabelaOrdens: document.getElementById("tabela_ordens"),
    tabelaCorpoOrdens: document.getElementById("corpo_tabela_ordens"),
    btnInicioPagOrdem: document.getElementById("inicio-ordens"),
    btnVoltarPagOrdem: document.getElementById("voltar-ordens"),
    btnProximaPaginaOrdem: document.getElementById("proximo-ordens"),
    btnUltimaPagOrdem: document.getElementById("ultimo-ordens"),
    popUpRegistroOrdens: document.getElementById(
      "popup_compra_entrada_saida_venda"
    ),
    btnFecharOrdem2: document.getElementById("btnFechar_ordem2"),
    formOrdemE: document.getElementById("form-ordem-entrada"),
    produtoFornecedor: document.getElementById("produto_fornecedor"),
    fornecedor: document.getElementById("fornecedor"),
    inserirOredemEntrada: document.getElementById("inserir_ordemComEnt"),
    btnSalvarEntrada: document.getElementById("salvar_ordemComEnt"),
    produtoNomeEntrada: document.getElementById("nome_produto_entrada"),
    paragrafoCodigoProduto: document.getElementById("paragrafo_codigo_produto"),
    paragrafoFornecedor: document.getElementById("paragrafo_fornecedor"),
    paragrafoCompraQuantidade: document.getElementById(
      "paragrafo_compra_quantidade"
    ),
    paragrafoNomeProdutoEntrada: document.getElementById(
      "paragrafo_nome_produto_entrada"
    ),
    popupSaida: document.getElementById("popup_saida_venda"),
    btnFecharOrdem3: document.getElementById("btnFechar_ordem3"),
    formOrdemS: document.getElementById("form-ordem-saida"),
    produtoCliente: document.getElementById("produto_cliente"),
    cliente: document.getElementById("cliente"),
    inserirOredemSaida: document.getElementById("inserir_ordemComSai"),
    btnSalvarSaida: document.getElementById("salvar_ordemComSai"),
    produtoNomeSaida: document.getElementById("nome_produto_saida"),
    paragrafoNomeProdutoSaida: document.getElementById(
      "paragrafo_nome_produto_saida"
    ),
    paragrafoCodigoProdutoSaida: document.getElementById(
      "paragrafo_codigo_produto_saida"
    ),
    paragrafoCliente: document.getElementById("paragrafo_cliente"),
    paragrafoSaidaQuantidade: document.getElementById(
      "paragrafo_saida_quantidade"
    ),
    popUpEditarOrdem: document.getElementById("editar_ordem"),
    pesquisarEditarOrdem: document.getElementById("pesquisar_editar_ordem"),
    btnEditarOrdens: document.getElementById("btn_editar_ordem"),
    btnFecharEditarOrdem: document.getElementById("btn_fechar_editar_ordem"),
    formPesquisarOrdemEditar: document.getElementById(
      "formulario_pesquisa_editar_ordem"
    ),
    paragrafoErroEditar: document.getElementById("pesquisar_ordem"),
    listaEditarOrdens: document.getElementById("lista_editar_ordens"),
    btnPesquisarOrdem: document.getElementById("btn_buscar_ordens_editar"),
    btnRemoverOrdem: document.getElementById("remover_ordem"),
    btnCarregarListaEditar: document.getElementById("carregar_ordens"),
    btnEditarOrdemEditar: document.getElementById("editar_ordem_editar"),
    formEditarOrdem: document.getElementById("form_editar_ordem"),
    abrirModalEditarOrdem: document.getElementById("editar_ordem_dentro"),
    inputEditarCodigo: document.getElementById("editar_codigo_produto"),
    inputEditarProduto: document.getElementById("editar_nome_produto"),
    inputEditarFornecedor: document.getElementById("editar_fornecedor"),
    inputEditarCliente: document.getElementById("editar_cliente"),
    inputEditarEntrada: document.getElementById("editar_entrada"),
    inputEditarSaida: document.getElementById("editar_saida"),
    paraagrafoErro1: document.getElementById("erro1"),
    paraagrafoErro2: document.getElementById("erro2"),
    paraagrafoErro3: document.getElementById("erro3"),
    paraagrafoErro4: document.getElementById("erro4"),
    paraagrafoErro5: document.getElementById("erro5"),
    paraagrafoErro6: document.getElementById("erro6"),
    btnSalvarEditarOrdem: document.getElementById("salvar_editar_ordem"),
    btnFecharEditarOrdemDentro: document.getElementById(
      "btn_fechar_editar_ordem_dentro"
    ),
    marcarTudoBtn: document.getElementById("marcar_tudo"),
  };
})(window.StockPro = window.StockPro || {});
